version: '3.8'

services:
  flarenet-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flarenet-editor-${USER_ID:-default}
    ports:
      - "${EDITOR_PORT:-3000}:3000"
      - "${PREVIEW_PORT:-5000}:5000"
    volumes:
      - ./source:/source:rw
      - editor-node-modules:/app/editor/node_modules
      - preview-node-modules:/app/preview/node_modules
    environment:
      - GIT_REPO=${GIT_REPO:-}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - GIT_USERNAME=${GIT_USERNAME:-}
      - GIT_TOKEN=${GIT_TOKEN:-}
      - AUTO_SYNC=${AUTO_SYNC:-false}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-60}
      - USER_ID=${USER_ID:-default}
      - PROJECT_ID=${PROJECT_ID:-default}
      - SOURCE_TYPE=${SOURCE_TYPE:-local} # local, git, or s3
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_KEY=${S3_KEY:-}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: ${MEMORY_LIMIT:-1G}

volumes:
  editor-node-modules:
  preview-node-modules: 